name: fa_flutter_ui_kit
description: Official FA Flutter UI Kit.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  progress_dialog: ^1.2.4
  rxdart: ^0.26.0
  flare_flutter: ^2.0.6
  cached_network_image: ^3.0.0-nullsafety
  keyboard_visibility: ^0.5.6
  device_info: ^2.0.0
  mobile_number_picker: ^0.0.1+4
  freezed_annotation: 0.12.0
  json_annotation: 3.1.1

  # Core
  fa_flutter_core:
    git:
      url: https://github.com/FieldAssist/fa_flutter_core.git
      ref: main

  # Api service
  fa_flutter_api_client:
    git:
      url: https://github.com/FieldAssist/fa_flutter_api_client.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.11.5
  freezed: 0.12.7
  json_serializable: 3.5.1

flutter:
  assets:
    - assets/images/
    - assets/flare/
