name: fa_flutter_ui_kit
description: Official FA Flutter UI Kit.
version: 1.0.0
homepage: https://github.com/FieldAssist/fa_flutter_ui_kit

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flare_flutter: ^3.0.2
  cached_network_image: ^3.2.0
  keyboard_visibility: ^0.5.6
  mobile_number_picker: ^0.0.1+5
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  jiffy: ^5.0.0
  flutter_svg: ^1.0.3
  shimmer: ^2.0.0

  #Location
  geolocator: ^8.2.0
  geocoding: ^2.0.2
  google_maps_flutter: ^2.1.1

  # Core
  fa_flutter_core:
    git:
      url: https://github.com/FieldAssist/fa_flutter_core.git
      ref: main

  # Api service
  fa_flutter_api_client:
    git:
      url: https://github.com/FieldAssist/fa_flutter_api_client.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  freezed: ^1.1.1
  json_serializable: ^6.1.4

flutter:
  assets:
    - assets/images/
    - assets/flare/
    - assets/data/

  fonts:
    - family: Trueno
      fonts:
        - asset: assets/fonts/TruenoBd.otf
          weight: 700
        - asset: assets/fonts/TruenoBdIt.otf
          weight: 700
          style: italic
        - asset: assets/fonts/TruenoLt.otf
          weight: 100
        - asset: assets/fonts/TruenoLtIt.otf
          weight: 100
          style: italic
        - asset: assets/fonts/TruenoRg.otf