name: fa_flutter_ui_kit
description: Official FA Flutter UI Kit.
version: 1.0.0
homepage: https://github.com/FieldAssist/fa_flutter_ui_kit

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mobile_number_picker: ^0.0.1+5
  qr_code_scanner: ^1.0.1
  speech_to_text: ^6.6.0
  flutter_tts: ^4.0.2
  file_picker: ^8.0.0+1
  open_file: ^3.3.2
 # todo:  change the version to 1.1.1 once flutter version is updated.
  safe_device: #^1.1.1
      git:
        url: https://github.com/Ritsz123/safe_device.git
        ref: fix/trust_location

  # Core
  fa_flutter_core:
    git:
      url: https://github.com/FieldAssist/fa_flutter_core.git
      ref: main

  # Api service
  fa_flutter_api_client:
    git:
      url: https://github.com/FieldAssist/fa_flutter_api_client.git
      ref: main
  decimal: ^3.0.2
  app_settings: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  assets:
    - assets/images/
    - assets/flare/
    - assets/data/

  fonts:
    - family: Trueno
      fonts:
        - asset: assets/fonts/TruenoBd.otf
          weight: 700
        - asset: assets/fonts/TruenoBdIt.otf
          weight: 700
          style: italic
        - asset: assets/fonts/TruenoLt.otf
          weight: 100
        - asset: assets/fonts/TruenoLtIt.otf
          weight: 100
          style: italic
        - asset: assets/fonts/TruenoRg.otf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_bd.ttf
          weight: 500
        - asset: assets/fonts/poppins_rg.ttf
          style: normal
        - asset: assets/fonts/poppins_lt.ttf
          weight: 200

