name: fa_flutter_ui_kit
description: Official FA Flutter UI Kit.
version: 1.0.0
homepage: https://github.com/FieldAssist/fa_flutter_ui_kit

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mobile_number_picker: ^0.0.1+5
  qr_code_scanner: ^1.0.1
  speech_to_text: ^6.1.1
  flutter_tts: ^3.6.3

  # Core
  fa_flutter_core:
    git:
      url: https://github.com/FieldAssist/fa_flutter_core.git
      ref: main

  # Api service
  fa_flutter_api_client:
    git:
      url: https://github.com/FieldAssist/fa_flutter_api_client.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  freezed: ^2.1.0
  json_serializable: ^6.1.4

flutter:
  assets:
    - assets/images/
    - assets/flare/
    - assets/data/

  fonts:
    - family: Trueno
      fonts:
        - asset: assets/fonts/TruenoBd.otf
          weight: 700
        - asset: assets/fonts/TruenoBdIt.otf
          weight: 700
          style: italic
        - asset: assets/fonts/TruenoLt.otf
          weight: 100
        - asset: assets/fonts/TruenoLtIt.otf
          weight: 100
          style: italic
        - asset: assets/fonts/TruenoRg.otf