name: Add contributors
on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  add-contributors:
    name: Add contributors to README.md
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: BobAnkh/add-contributors@master
        with:
          REPO_NAME: 'FieldAssist/fa_flutter_ui_kit'
          CONTRIBUTOR: '## ✨ Active Contributors'
          COLUMN_PER_ROW: '6'
          ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
          IMG_WIDTH: '100'
          FONT_SIZE: '14'
          PATH: '/README.md'
          COMMIT_MESSAGE: '[README] Update contributors'
          AVATAR_SHAPE: 'square'